[[redirects]]
  from = "/api"
  to = "https://cryptic-woodland-28293.herokuapp.com/api/*"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
